import random

tips_dict = {
    "Eat a healthy breakfast": "Eating breakfast starts your day off on the right foot and gives you fuel for the day that will help you make better food decisions throughout the day.",
    "Get moving": "Walk where you can, whenever you can. Walk to a co-worker’s desk instead of sending an email. Take a lap around the block. You don’t have to take long or intense walks, but try to add a few more steps to your day.",
    "Find a workout buddy": "It may not be for everyone, but for a lot of people, having a buddy to meet for workouts helps with accountability and enjoyability. If your friends’ workout schedules don’t work with yours, check out our small group training and group exercise options.",
    "Make it easier to get a full night’s sleep": "Blocking out unwanted noise, keeping your room cooler and making sure your bedroom is dark enough are all ways to help perfect your sleeping environment",
    "Play with your pet": "Your furry friend does a great job of reducing stress in your life, and reducing stress in your life makes it easier to keep your fitness goals. Also, putting effort into playtime with your pet may be a great way to get your MEPs for the day!",
    "Spend time with positive people": "When getting started with a new habit or lifestyle change, it’s important to surround yourself with people who support you and can give you encouragement. Make plans with your support system this week to absorb some positivity.",
    "Review your MYZONE app/emails": "Seeing what you have accomplished will keep you motivated, allow you to see your progress and keep you focused on your goals.",
    "Make food changes slowly": "Don’t try to change everything at once! Instead of making drastic changes all at once, make a few small adjustments every week or month to help you get where you want to be. Try a new food or modify the proportions you eat, and let your body acclimate between changes.",
    "Eight (8-ounce) cups of water a day": "The amount of water each person needs can vary, but eight cups a day is a good rule of thumb (possibly more depending on your activity level). With all the MYZONE workouts you’ll be completing, be sure to stay hydrated!",
    "Start your day off with positive thoughts": "What are you looking forward to? What fun or exciting things may happen today? We’re not telling you to forget any negative or worrisome things you are dealing with in your life, just remind yourself of the things that can and do give you a sense of calm or put a smile on your face. For those interested, we also offer meditation classes at the Staenberg Family Complex as part of our group exercise schedule! Join us on Fridays at 7am.",
    "Exchange the elevator for the stairs": "There’s a reason we have stair climbers at the J – getting those steps in is great exercise. Adding more flights of stairs into your routine can increase your conditioning as well!",
    "Meal prep & cook ahead": "Resorting to fast food or vending machine snacks is often the result of not having a better option easily available. Making a plan for the week can help you schedule in time to prepare your food while juggling all of your weekly responsibilities. Try to set aside a few hours to make a few meals all at once, and you can start your week off with all your meals ready to go!",
    "Fit in a short workout before your shower": "Give yourself a few extra minutes before you shower to fit in some bodyweight exercises. Or, do them before you make your bed in the morning or after doing your dinner dishes. Pick a regular moment during your daily routine and commit to a few exercises. Squats, lunges, push-ups, sit-ups and planks are all easy to fit in – no matter the room of your house!",
    "Go to bed at the same time every night": "Or at least as much as possible. Everyone’s schedule changes, but training your body to begin the sleep process at a similar time each evening can help you fall asleep more quickly and prevent those nights of restless tossing and turning.",
    "Try short but intense workouts": "Don’t have 45 minutes to spend at the gym every evening? Squeeze in a high-intensity interval training (HIIT) workout This type of workout alternates short periods of maximum effort with less intense recovery periods. Think jump rope workouts, sprinting intervals on the treadmill, circuit training and more. The J offers HIIT classes as part of our group exercise schedule.",
    "Go shopping on a full stomach": "Avoid that moment in the grocery store when you watch your favorite unhealthy food make its way into your cart. When you’re hungry, you’re more likely to buy more food than you need and to let those unhealthy foods you crave make their way back to your home.",
    "Stop doing anything in your best except for sleep and sex": "Make your night’s sleep better by conditioning your body. Scale back your use of devices and TV before you’re in bed.",
    "Dine out less frequently": "Save money and calories. By making your meals at home, you can monitor what actually goes into your food and the portion size. If you do go out to eat – think about substituting our your sides for steamed vegetables!",
    "Make sure you are using proper form": "You’ve probably heard this from our trainers before, but this is a super important tip. The lack of proper forms makes you more likely to get injured, less likely to get stronger, and guarantees that you will look silly on the fitness floor. Before starting a new exercise, double check the proper form. And, remember, our trainers are here to help! Inquire at the fitness desk.",
    "Get organized and set priorities and deadlines": " Stress makes sticking to your fitness and diet plan even harder, and a lack of organization can add to your stress. So, outline some projects (home, monetary, work, etc.) that can help you organize pieces of your daily life and help you reduce stress.",
    "Stop smoking": "We’re sure you’ve heard it before, but we have to remind you. Quitting smoking can not only help you increase your fitness level but also your day-to-day health as well. We know this is a challenge, so it’s important to find resources that can support you in this process. Check out these tips from the American Lung Association.",
    "Do your grocery shopping with a list in hand": "Making a list before getting to the grocery store can help you say no to impulse buys or giving into those snacks that look super tasty. Plan our your meals, make a list of the ingredients needed and stick to your list.",
    "Exercise during TV commercials": "When a commercial starts, make the most of that downtime. You don’t need to plan anything too intense – set a squat or a pushup goal, walk through your entire house or hold a plank as long as possible. Have a Netflix-only household? Set a timer on your phone to remind you to get up every ten minutes to fit in a short exercise.",
    "Take Naps!": "leep deprivation can affect all aspects of your life: your diet, your workouts, your stress, etc. Don’t feel guilty about squeezing in a short nap to help your body recharge. A 30-minute nap or even an extended rest period of laying down (without a nap) have been found to improve alertness and performance.",
    "Avoid people and things that stress you out": "Identify stressors in your life and try to keep a distance. It’s not always possible to do, but removing anything causing you stress is an improvement. If the stress can’t be removed, can it be improved? Brainstorm ways to reduce these stress points in your day-to-day life. You can always ask for help too! Your friends are good resources to ask about how to approach these issues.",
    "Laugh and smile!": "Celebrate those moments that make you happy. Taking time to express your positive emotions can impact your health and happiness. Laughter helps to cope with stress and can boost your mood (event forced laughter can give you a temporary boost).",
    "Balance your carbohydrates, fats, protein, etc. in each meal": "Balance your carbohydrates, fats, protein, etc. in each meal.",
    "Warm up before and cool down after your workouts": "It’s not a waste of time, it’s the best a way to reduce your risk of injury and improve your performance. Let’s start with the warm-up. Your warm-up is designed to prepare you for the workout ahead. Therefore, the way you warm up will vary depending on what you plan to do in your workout. A warm-up for a jog would involve walking. A warm-up before lifting weights would involve performing some lighter weight sets. Use MYZONE to help your warm-up by working a few minutes in the gray, move up to blue, then to green, and finally yellow/red if desired. Cool down by performing your workout at a lower intensity or walking until your heart rate lowers. And, don’t forget stretching!",
    "Don’t add salt to your food": "If you’re already eating whole, fresh foods, this isn’t such a big issue, however, most packaged foods already contain high levels of sodium, so adding more only increases your intake. Most Americans consume more than double the recommended level of sodium a day (2,300 mg), which can raise blood pressure and lead to heart disease and stroke.",
    "Make dark chocolate your ‘indulgence food.’": "In case you haven’t heard, dark chocolate is better for you than milk or white chocolate. One of the biggest benefits of dark chocolate is that it can lead to a decrease in blood pressure (with a healthy diet). Aim for dark chocolate with a cacao percentage of at least 70% to reap these health benefits, and, as with all indulgences, moderation is key.",
}


def get_tip():
    title, content = random.choice(list(tips_dict.items()))
    return {'title': title, 'content': content}

